In [17]:
import pandas as pd

# Load Data Raw

In [18]:
df_cnn = pd.read_excel('cnn_indonesia.xlsx')
df_tbh = pd.read_excel('turnbackhoax.xlsx')

In [19]:
print(f"Jumlah data CNN: {len(df_cnn)}")
print(f"Jumlah data Turnbackhoax: {len(df_tbh)}")

Jumlah data CNN: 2675
Jumlah data Turnbackhoax: 1484

In [20]:
# --- CEK INFO DATA MENTAH CNN ---
print("--- INFO DATA MENTAH CNN INDONESIA ---")
df_cnn.info()

--- INFO DATA MENTAH CNN INDONESIA ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2675 entries, 0 to 2674
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  2675 non-null   object
 1   Title      2675 non-null   object
 2   FullText   2675 non-null   object
 3   Category   2675 non-null   object
dtypes: object(4)
memory usage: 83.7+ KB

In [21]:
# --- CEK INFO DATA MENTAH TURNBACKHOAX ---
print("\n--- INFO DATA MENTAH TURNBACKHOAX ---")
df_tbh.info()

--- INFO DATA MENTAH TURNBACKHOAX ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  1484 non-null   object
 1   Title      1484 non-null   object
 2   FullText   1484 non-null   object
 3   Category   1484 non-null   object
dtypes: object(4)
memory usage: 46.5+ KB

In [22]:
# Menentukan kolom yang akan ditampilkan
kolom_pilihan = ['Timestamp', 'Title', 'FullText', 'Category']

# Mengatur tampilan agar menampilkan total 10 baris (5 atas, 5 bawah) dengan titik-titik di tengah
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_colwidth', 40)
print(f"Jumlah data CNN Indonesia: {len(df_cnn)}")
print("\n--- Preview Dataset CNN Indonesia (Struktur Awal) ---")

# Menampilkan dataset secara keseluruhan (otomatis muncul ... di tengah)
display(df_cnn[kolom_pilihan])
print("-" * 60)
print(f"Jumlah data Turnbackhoax: {len(df_tbh)}")
print("\n--- Preview Dataset Turnbackhoax (Struktur Awal) ---")

display(df_tbh[kolom_pilihan])

Jumlah data CNN Indonesia: 2675

--- Preview Dataset CNN Indonesia (Struktur Awal) ---

                Timestamp                                    Title                                 FullText Category
0     2024-01-04 00:00:00  Marzuki Mustamar Eks PWNU Jatim Ungk...  Marzuki Mustamar buka-bukaan soal Su...  Politik
1              04/01/2024  Revisi UU ITE Jilid II Resmi Berlaku...  Presiden Joko Widodo menandatangani ...  Politik
2              02/01/2024  Senator Bali Arya Wedakarna Buka Sua...  Anggota DPD RI atau senator asal Bal...  Politik
3              02/01/2024  PWNU Jatim Dapat Karangan Bunga Prot...  Kantor Pengurus Wilayah Nahdlatul Ul...  Politik
4              02/01/2024  Jokowi Ingin Pulang ke Solo Usai Jab...  Presiden Joko Widodo (Jokowi) mengut...  Politik
...                   ...                                      ...                                      ...      ...
2670           02/01/2025  MK Putuskan 4 Gugatan Ambang Batas C...  Mahkamah Konstitusi (MK) akan memutu...  Politik
2671           01/01/2025  Anggota DPR Klaim Akan Jalan Kaki Ja...  Anggota DPR RI dari Dapil V Jawa Ten...  Politik
2672           01/01/2025  PKB soal PPN 12 Persen ke Barang Mew...  Ketua Umum Partai Kebangkitan Bangsa...  Politik
2673           01/01/2025  PKB Pamer Kekuatan 2024: Suara Pileg...  Wakil Ketua Umum PKB Cucun Ahmad Sya...  Politik
2674           31/12/2024  Jubir PDIP soal Hasto bersama Harun ...  PDIP membantah Sekretaris Jenderal P...  Politik

[2675 rows x 4 columns]

------------------------------------------------------------
Jumlah data Turnbackhoax: 1484

--- Preview Dataset Turnbackhoax (Struktur Awal) ---

       Timestamp                                    Title                                 FullText Category
0     02/01/2024  najwa shihab diteror usai komentari ...  Akun TikTok @beritatangguh mengungga...  Politik
1     03/01/2024  video jokowi menyaksikan debat cawapres  Sebuah akun TikTok membagikan video ...  Politik
2     04/01/2024  nasdem akui terima aliran dana korup...  Akun TikTok @r4kyatjelata mengunggah...  Politik
3     04/01/2024  nama anies baswedan masuk dalam daft...  Akun TikTok @matanies mengunggah vid...  Politik
4     04/01/2024  hanya gibran yang memakai microphone...  Akun Facebook roger.silalahi_officia...  Politik
...          ...                                      ...                                      ...      ...
1479  26/11/2024  penipuan prabowo kabulkan kenaikan g...  Tim Pemeriksa Fakta Mafindo (TurnBac...  Politik
1480  26/11/2024  prabowo gaji tni harus naik dua kali...  Tim Pemeriksa Fakta Mafindo (TurnBac...  Politik
1481  26/11/2024  tom lembong bocorkan bobrok jokowi k...  Tim Pemeriksa Fakta Mafindo (TurnBac...  Politik
1482  27/11/2024  prabowo bakal posisikan polri di baw...  Tim Pemeriksa Fakta Mafindo (TurnBac...  Politik
1483  27/11/2024  pramono anung gusur warga nggak masa...  Tim Pemeriksa Fakta Mafindo (TurnBac...  Politik

[1484 rows x 4 columns]

In [23]:
# 2. Setting agar teks tampil panjang ke samping tanpa dipotong titik-titik di tengah
pd.set_option('display.max_colwidth', 500) 

# 3. Menampilkan 5 Sampel Data CNN Indonesia
print("--- SAMPEL 5 DATA MENTAH CNN INDONESIA ---")
display(df_cnn[['Timestamp', 'Title', 'FullText', 'Category']].head(5))

print("\n--- SAMPEL 5 DATA MENTAH TURNBACKHOAX ---")
display(df_tbh[['Timestamp', 'Title', 'FullText', 'Category']].head(5))

# 4. Kembalikan ke default agar output kodingan lain tidak terlalu lebar
pd.reset_option('display.max_colwidth')

--- SAMPEL 5 DATA MENTAH CNN INDONESIA ---

             Timestamp                                                               Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             FullText Category
0  2024-01-04 00:00:00   Marzuki Mustamar Eks PWNU Jatim Ungkap Kejanggalan 3 SP dari PBNU  Marzuki Mustamar buka-bukaan soal Surat Peringatan (SP) sebanyak tiga kali yang dilayangkan oleh PBNU sebelum ia dicopot dari Ketua PWNU Jatim. Marzuki membenarkan adanya SP tersebut. Namun, sampai sekarang dia tidak begitu paham kesalahan yang dimaksud oleh PBNU.\n"Kami tidak tahu ya (kesalahan yang dilakukan)," beber Marzuki mengutip detikcom, Kamis (4/1)\nMarzuki lantas membeberkan poin-poin yang tertulis di dalam SP PBNU. Salah satunya disebutkan bahwa dia menentang perintah PBNU. Marzuk...  Politik
1           04/01/2024          Revisi UU ITE Jilid II Resmi Berlaku, Sudah Diteken Jokowi  Presiden Joko Widodo menandatangani revisi Undang-Undang Informasi dan Transaksi Elektronik (UU ITE) atau yang dikenal dengan UU ITE jilid II.\nPenandatanganan dan pengundangan dilakukan Selasa (2/1). Kementerian Sekretariat Negara telah mengunggah salinan undang-undang itu di situs mereka.\n"Salinan Undang-Undang Nomor 1 Tahun 2024 disahkan tanggal 02 Januari 2024, diundangkan tanggal 02 Januari 2024," dikutip dari situs resmi Jaringan Dokumentasi dan Informasi Hukum Kementerian Sekretariat...  Politik
2           02/01/2024      Senator Bali Arya Wedakarna Buka Suara soal Viral Ucapan Hijab  Anggota DPD RI atau senator asal Bali Arya Wedakarna (AWK) menyampaikan klarifikasi usai viral di media sosial menyinggung penggunaan hijab untuk perempuan muslimah.\n"Atas masukan daripada tokoh bangsa dan juga para pelingsir di Provinsi Bali maka saya mengklarifikasi terkait dengan beredarnya potongan dari acara rapat kerja kami Selaku Komite l Bidang Hukum DPD RI utusan Provinsi Bali," kata Arya dalam video klarifikasi yang diunggah di akun instagramnya.\nPoin pertama Arya mengklarifikasi...  Politik
3           02/01/2024   PWNU Jatim Dapat Karangan Bunga Protes Pemecatan Marzuki Mustamar  Kantor Pengurus Wilayah Nahdlatul Ulama (PWNU) Jawa Timur mendapat kiriman bunga usai pencopotan Marzuki Mustamar sebagai ketua. Seluruh rangkaian bunga itu bernada protes terhadap Pengurus Besar Nahdlatul Ulama (PBNU).\nSetidaknya ada delapan karangan bunga yang diletakkan pengirim di halaman sebelah utara PWNU Jatim atau di akses menuju pintu masuk, sejak Minggu (31/12).\nPekerja yang mengirimkan bunga, Siswanto mengaku tidak mengetahui siapa yang pemesan karangan bunga tersebut. Ia hanya ...  Politik
4           02/01/2024  Jokowi Ingin Pulang ke Solo Usai Jabat Presiden: Jadi Rakyat Biasa  Presiden Joko Widodo (Jokowi) mengutarakan keinginannya untuk pulang ke kampung halamannya di Solo, Jawa Tengah, setelah menuntaskan masa jabatannya pada Oktober 2024.\nIa mengaku ingin menjadi rakyat biasa setelah 10 tahun menjabat jadi presiden.\n\nADVERTISEMENT\nSCROLL TO CONTINUE WITH CONTENT\n"Ya jadi rakyat biasa, kembali ke Solo jadi rakyat biasa," kata Jokowi usai mengunjungi pasar tradisional di Purworejo, Jawa Tengah, Selasa (2/1).\nSaat ditanya apakah ia berminat menjadi Sekretari...  Politik

--- SAMPEL 5 DATA MENTAH TURNBACKHOAX ---

    Timestamp                                                                           Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             FullText Category
0  02/01/2024                               najwa shihab diteror usai komentari video prabowo  Akun TikTok @beritatangguh mengunggah video dengan klaim bahwa jurnalis senior, Najwa Shihab, menerima teror dan ancaman setelah dirinya memberikan komentar mengenai video Prabowo Subianto di acara Debat Cawapres pada 22 Desember 2023. Dalam momen tersebut, diketahui bahwa Prabowo sempat menarik kerah jaket yang dipakai Menteri Investasi, Bahlil Lahadalia. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Najwa Shihab telah mengomentari video Prabo...  Politik
1  03/01/2024                                         video jokowi menyaksikan debat cawapres  Sebuah akun TikTok membagikan video yang menampilkan Presiden Jokowi tengah menyaksikan Debat Calon Wakil Presiden (Cawapres) pada 22 Desember lalu. Video itu memperlihatkan foto Jokowi dari belakang menggunakan kaos kasual berwarna hijau tosca. Terdapat layar monitor yang cukup besar di depan Jokowi, layar itu menampilkan sesi debat cawapres. Faktanya unggahan TikTok tersebut merupakan hasil manipulasi, pengunggah menggabungkan foto dan video dalam satu frame. Hal ini membuat video seperti ...  Politik
2  04/01/2024                 nasdem akui terima aliran dana korupsi dari syahrul yasin limpo  Akun TikTok @r4kyatjelata mengunggah video dengan klaim bahwa Partai Nasional Demokrat (NasDem) mengaku telah menerima aliran dana korupsi dari mantan Menteri Pertanian, Syahrul Yasin Limpo (SYL), yang sebelumnya diduga menikmati hasil uang korupsi senilai Rp 13,9 M. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Partai NasDem mengaku telah menerima aliran dana korupsi dari SYL seperti yang tertulis pada unggahan. Partai NasDem melalui bendahara...  Politik
3  04/01/2024  nama anies baswedan masuk dalam daftar penikmat uang hasil korupsi bts kominfo  Akun TikTok @matanies mengunggah video dengan klaim bahwa nama Anies Baswedan masuk dalam daftar penikmat uang hasil korupsi proyek BTS 4G Kementerian Komunikasi dan Informatika (Kominfo) yang melibatkan mantan Sekjen Nasdem, Johnny G. Plate. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Anies Baswedan turut menikmati uang hasil korupsi BTS 4G Kominfo seperti yang diklaim pada unggahan. Berdasarkan artikel milik CNN Indonesia berjudul “Daftar 1...  Politik
4  04/01/2024          hanya gibran yang memakai microphone yang dipegang saat debat cawapres  Akun Facebook roger.silalahi_official memposting gambar yang menunjukan foto Cawapres dari nomor 1-3 saat debat Cawapres. Dalam postingan tersebut mengklaim bahwa hanya Gibran Cawapres nomor 2 yang diberi microphone yang dialih fungsikan menjadi alat bantu dengar. Setelah ditelusuri dengan membandingkan alat yang digunakan Cawapres saat debat pada Jumat, 22 Desember 2023 ketiga Cawapres baik Cak Imin, Mahfud dan Gibran sama sama memakai 3 alat diantaranya microphone yang di pegang, mic di da...  Politik

# Pemberian Label

In [24]:
# CNN Indonesia = 0 (Valid)
# Turnbackhoax = 1 (Hoaks)
df_cnn['label'] = 0
df_tbh['label'] = 1

In [25]:
# 2. Melihat sampel data untuk memastikan label sudah terisi benar
print("\n--- Sampel 10 Data Teratas CNN (Valid - 0) ---")
display(df_cnn[['Title', 'FullText', 'label']].head(10))

--- Sampel 10 Data Teratas CNN (Valid - 0) ---

                                               Title                                           FullText  label
0  Marzuki Mustamar Eks PWNU Jatim Ungkap Kejangg...  Marzuki Mustamar buka-bukaan soal Surat Pering...      0
1  Revisi UU ITE Jilid II Resmi Berlaku, Sudah Di...  Presiden Joko Widodo menandatangani revisi Und...      0
2  Senator Bali Arya Wedakarna Buka Suara soal Vi...  Anggota DPD RI atau senator asal Bali Arya Wed...      0
3  PWNU Jatim Dapat Karangan Bunga Protes Pemecat...  Kantor Pengurus Wilayah Nahdlatul Ulama (PWNU)...      0
4  Jokowi Ingin Pulang ke Solo Usai Jabat Preside...  Presiden Joko Widodo (Jokowi) mengutarakan kei...      0
5         Jokowi Sebut Belum Dapat Undangan HUT PDIP  Presiden Joko Widodo (Jokowi) mengaku belum me...      0
6  Djarot Soal HUT PDIP: Pak Jokowi Diundang Pun ...  Ketua DPP PDIP Djarot Saiful Hidayat menilai P...      0
7  Usai dengan Prabowo & Airlangga, Kini Jokowi M...  Presiden Joko Widodo dan Menteri Perdagangan y...      0
8  3 Analisis Hasto PDIP Soal Pertemuan Empat Mat...  Sekjen PDIP Hasto Kristiyanto mengungkap tiga ...      0
9  Hasto Ungkap Jokowi Kunjungi Filipina saat HUT...  Sekretaris Jendral PDI Perjuangan Hasto Kristi...      0

In [26]:
print("\n--- Sampel 10 Data Teratas Turnbackhoax (Hoaks - 1) ---")
display(df_tbh[['Title', 'FullText', 'label']].head(10))

--- Sampel 10 Data Teratas Turnbackhoax (Hoaks - 1) ---

                                               Title                                           FullText  label
0  najwa shihab diteror usai komentari video prabowo  Akun TikTok @beritatangguh mengunggah video de...      1
1            video jokowi menyaksikan debat cawapres  Sebuah akun TikTok membagikan video yang menam...      1
2  nasdem akui terima aliran dana korupsi dari sy...  Akun TikTok @r4kyatjelata mengunggah video den...      1
3  nama anies baswedan masuk dalam daftar penikma...  Akun TikTok @matanies mengunggah video dengan ...      1
4  hanya gibran yang memakai microphone yang dipe...  Akun Facebook roger.silalahi_official memposti...      1
5  partai demokrat merapat ke pdip dan siap menan...  Akun TikTok @r4kyatjelata mengunggah video den...      1
6  sby tuduh jokowi sebagai dalang dari pecahnya ...  Akun TikTok @r4kyatjelata mengunggah video den...      1
7          anies berikan tutorial cara memasak kodok  Beredar sebuah video yang diunggah di media so...      1
8  cover majalah time 2023 benjamin netanyahu dis...  Akun Twitter @WeThePeople3009 (Shenaz) mengung...      1
9            rohingnya mulai masuk kenjeran surabaya  PENJELASAN: Akun TikTok SATE SARAWAK ORIGINAL ...      1

# Penggabungan Atribut

In [27]:
# Penggabungan Atribut (Title + FullText)
df_cnn['text_original'] = df_cnn['Title'].astype(str) + " " + df_cnn['FullText'].astype(str)
df_tbh['text_original'] = df_tbh['Title'].astype(str) + " " + df_tbh['FullText'].astype(str)

In [28]:
# --- PENGATURAN VISUALISASI RAPI (10 BARIS) ---
pd.set_option('display.max_rows', 10)     # 5 atas, 5 bawah dengan ... di tengah
pd.set_option('display.max_colwidth', 40) # Lebar kolom dibatasi agar ringkas di dokumen

print(f"Total Data CNN: {len(df_cnn)} baris")
print("--- Preview Validasi Penggabungan Kolom (CNN Indonesia) ---")
display(df_cnn[['Title', 'FullText', 'text_original']])

print("-" * 85)

print(f"Total Data Turnbackhoax: {len(df_tbh)} baris")
print("--- Preview Validasi Penggabungan Kolom (Turnbackhoax) ---")
display(df_tbh[['Title', 'FullText', 'text_original']])

Total Data CNN: 2675 baris
--- Preview Validasi Penggabungan Kolom (CNN Indonesia) ---

                                        Title                                 FullText                            text_original
0     Marzuki Mustamar Eks PWNU Jatim Ungk...  Marzuki Mustamar buka-bukaan soal Su...  Marzuki Mustamar Eks PWNU Jatim Ungk...
1     Revisi UU ITE Jilid II Resmi Berlaku...  Presiden Joko Widodo menandatangani ...  Revisi UU ITE Jilid II Resmi Berlaku...
2     Senator Bali Arya Wedakarna Buka Sua...  Anggota DPD RI atau senator asal Bal...  Senator Bali Arya Wedakarna Buka Sua...
3     PWNU Jatim Dapat Karangan Bunga Prot...  Kantor Pengurus Wilayah Nahdlatul Ul...  PWNU Jatim Dapat Karangan Bunga Prot...
4     Jokowi Ingin Pulang ke Solo Usai Jab...  Presiden Joko Widodo (Jokowi) mengut...  Jokowi Ingin Pulang ke Solo Usai Jab...
...                                       ...                                      ...                                      ...
2670  MK Putuskan 4 Gugatan Ambang Batas C...  Mahkamah Konstitusi (MK) akan memutu...  MK Putuskan 4 Gugatan Ambang Batas C...
2671  Anggota DPR Klaim Akan Jalan Kaki Ja...  Anggota DPR RI dari Dapil V Jawa Ten...  Anggota DPR Klaim Akan Jalan Kaki Ja...
2672  PKB soal PPN 12 Persen ke Barang Mew...  Ketua Umum Partai Kebangkitan Bangsa...  PKB soal PPN 12 Persen ke Barang Mew...
2673  PKB Pamer Kekuatan 2024: Suara Pileg...  Wakil Ketua Umum PKB Cucun Ahmad Sya...  PKB Pamer Kekuatan 2024: Suara Pileg...
2674  Jubir PDIP soal Hasto bersama Harun ...  PDIP membantah Sekretaris Jenderal P...  Jubir PDIP soal Hasto bersama Harun ...

[2675 rows x 3 columns]

-------------------------------------------------------------------------------------
Total Data Turnbackhoax: 1484 baris
--- Preview Validasi Penggabungan Kolom (Turnbackhoax) ---

                                        Title                                 FullText                            text_original
0     najwa shihab diteror usai komentari ...  Akun TikTok @beritatangguh mengungga...  najwa shihab diteror usai komentari ...
1     video jokowi menyaksikan debat cawapres  Sebuah akun TikTok membagikan video ...  video jokowi menyaksikan debat cawap...
2     nasdem akui terima aliran dana korup...  Akun TikTok @r4kyatjelata mengunggah...  nasdem akui terima aliran dana korup...
3     nama anies baswedan masuk dalam daft...  Akun TikTok @matanies mengunggah vid...  nama anies baswedan masuk dalam daft...
4     hanya gibran yang memakai microphone...  Akun Facebook roger.silalahi_officia...  hanya gibran yang memakai microphone...
...                                       ...                                      ...                                      ...
1479  penipuan prabowo kabulkan kenaikan g...  Tim Pemeriksa Fakta Mafindo (TurnBac...  penipuan prabowo kabulkan kenaikan g...
1480  prabowo gaji tni harus naik dua kali...  Tim Pemeriksa Fakta Mafindo (TurnBac...  prabowo gaji tni harus naik dua kali...
1481  tom lembong bocorkan bobrok jokowi k...  Tim Pemeriksa Fakta Mafindo (TurnBac...  tom lembong bocorkan bobrok jokowi k...
1482  prabowo bakal posisikan polri di baw...  Tim Pemeriksa Fakta Mafindo (TurnBac...  prabowo bakal posisikan polri di baw...
1483  pramono anung gusur warga nggak masa...  Tim Pemeriksa Fakta Mafindo (TurnBac...  pramono anung gusur warga nggak masa...

[1484 rows x 3 columns]

In [29]:
# --- VALIDASI PENGGABUNGAN TEKS SECARA UTUH (CNN INDONESIA) ---

# 1. Matikan batasan lebar kolom agar teks terlihat semua tanpa dipotong (...)
pd.set_option('display.max_colwidth', None)

# 2. Pengaturan tampilan baris
pd.set_option('display.max_rows', 10)

print("--- Preview Hasil Penggabungan CNN Indonesia (Teks Utuh) ---")

# Menampilkan 5 data teratas (Awal)
display(df_cnn[['Title', 'FullText', 'text_original']].head(5))

print("-" * 30 + " Dan seterusnya (Data Tengah) " + "-" * 30)

# Menampilkan 5 data terbawah (Akhir)
display(df_cnn[['Title', 'FullText', 'text_original']].tail(5))

--- Preview Hasil Penggabungan CNN Indonesia (Teks Utuh) ---

                                                                Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FullText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text_original

------------------------------ Dan seterusnya (Data Tengah) ------------------------------

                                                                       Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FullText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       text_original
2670              MK Putuskan 4 Gugatan Ambang Batas Calon Presiden Hari Ini                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Mahkamah Konstitusi (MK) akan memutuskan empat permohonan uji materi terkait pengaturan ambang batas pencalonan presiden (presidential threshold) yang diatur dalam UU No. 7 Tahun 2017 tentang Pemilu pada sidang yang digelar di Gedung MK, Jakarta, hari ini Kamis (2/1).\nDikutip jadwal sidang di laman resmi MK, setidaknya ada empat gugatan yang diajukan terkait persyaratan ambang batas pencalonan presiden akan diputuskan hari ini.\nEmpat gugatan yang akan diputuskan ini terregistrasi pada perkara 62/PUU-XXII/2024 yang diajukan oleh Enika Maya Oktavia dan perkara No. 101/PUU-XXI/2024 diajukan oleh Yayasan Jaringan Demokrasi dan Pemilu Berintegritas (NETGRIT).\nADVERTISEMENT\nSCROLL TO CONTINUE WITH CONTENT\nKemudian terdapat perkara No. 87/PUU-XXII/2024 yang diajukan oleh Dian Fitri Sabrina, Muhammad, Muchtadin Alatas dan Muhammad Saad. Lalu terdapat perkara nomor 129/PUU-XXI/2023 yang diajukan oleh Gugum Ridho Putra.\n\nDalam gugatannya, pada intinya para pemohon menggugat pasal 222 UU Pemilu yang mengatur tentang presidential threshold berupa 20 persen kursi DPR atau 25 persen suara nasional.\nPasal 222 UU Pemilu telah mengatur persyaratan capres-cawapres hanya dapat dicalonkan oleh parpol yang memiliki minimal 20 persen kursi DPR atau memperoleh 25 persen suara sah nasional pada pemilu sebelumnya.\n"Pasangan Calon diusulkan oleh Partai Politik atau Gabungan Partai Politik Peserta Pemilu yang memenuhi persyaratan perolehan kursi paling sedikit 20% (dua puluh persen) dari jumlah kursi DPR atau memperoleh 25% (dua puluh lima persen) dari suara sah secara nasional pada Pemilu anggota DPR sebelumnya," bunyi pasal tersebut.\nMK pernah memutuskan perkara yang sama atau serupa pada putusan sebelumnya. Hakim Konstitusi Saldi Isra pada Februari 2024 lalu pernah menyampaikan norma pada pasal 222 itu telah diuji sebanyak 27 kali dengan lima amar putusan ditolak dan sisanya tidak dapat diterima.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MK Putuskan 4 Gugatan Ambang Batas Calon Presiden Hari Ini Mahkamah Konstitusi (MK) akan memutuskan empat permohonan uji materi terkait pengaturan ambang batas pencalonan presiden (presidential threshold) yang diatur dalam UU No. 7 Tahun 2017 tentang Pemilu pada sidang yang digelar di Gedung MK, Jakarta, hari ini Kamis (2/1).\nDikutip jadwal sidang di laman resmi MK, setidaknya ada empat gugatan yang diajukan terkait persyaratan ambang batas pencalonan presiden akan diputuskan hari ini.\nEmpat gugatan yang akan diputuskan ini terregistrasi pada perkara 62/PUU-XXII/2024 yang diajukan oleh Enika Maya Oktavia dan perkara No. 101/PUU-XXI/2024 diajukan oleh Yayasan Jaringan Demokrasi dan Pemilu Berintegritas (NETGRIT).\nADVERTISEMENT\nSCROLL TO CONTINUE WITH CONTENT\nKemudian terdapat perkara No. 87/PUU-XXII/2024 yang diajukan oleh Dian Fitri Sabrina, Muhammad, Muchtadin Alatas dan Muhammad Saad. Lalu terdapat perkara nomor 129/PUU-XXI/2023 yang diajukan oleh Gugum Ridho Putra.\n\nDalam gugatannya, pada intinya para pemohon menggugat pasal 222 UU Pemilu yang mengatur tentang presidential threshold berupa 20 persen kursi DPR atau 25 persen suara nasional.\nPasal 222 UU Pemilu telah mengatur persyaratan capres-cawapres hanya dapat dicalonkan oleh parpol yang memiliki minimal 20 persen kursi DPR atau memperoleh 25 persen suara sah nasional pada pemilu sebelumnya.\n"Pasangan Calon diusulkan oleh Partai Politik atau Gabungan Partai Politik Peserta Pemilu yang memenuhi persyaratan perolehan kursi paling sedikit 20% (dua puluh persen) dari jumlah kursi DPR atau memperoleh 25% (dua puluh lima persen) dari suara sah secara nasional pada Pemilu anggota DPR sebelumnya," bunyi pasal tersebut.\nMK pernah memutuskan perkara yang sama atau serupa pada putusan sebelumnya. Hakim Konstitusi Saldi Isra pada Februari 2024 lalu pernah menyampaikan norma pada pasal 222 itu telah diuji sebanyak 27 kali dengan lima amar putusan ditolak dan sisanya tidak dapat diterima.\n
2671      Anggota DPR Klaim Akan Jalan Kaki Jakarta-Boyolali, Target 11 Hari                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Anggota DPR RI dari Dapil V Jawa Tengah, Didik Haryadi mengaku akan berjalan kaki dari Jakarta menuju Boyolali, Jawa Tengah sebagai bentuk menunaikan janji. Perjalanan dimulai dari kawasan parlemen di Senayan, Jakarta ke Boyolali, hari ini, Rabu (1/1).\nDilansir dari Antara, Didik mengatakan jalan kaki ini adalah pelaksanaan dari janjinya kepada Allah.\n"Setiap orang pernah berjanji di hadapan Tuhan, dan saya ingin menepati janji itu selama saya masih diberi kesempatan hidup," kata Didik di kompleks parlemen, Senayan, Jakarta, Rabu (1/1).\nADVERTISEMENT\nSCROLL TO CONTINUE WITH CONTENT\n\nSelain itu ia juga mengaku pernah bernazar bila terpilih menjadi anggota DPR RI maka akan berjalan kaki dari Senayan, Jakarta, menuju Boyolali.\nNazar ini menurutnya jadi bentuk komitmen dirinya untuk memperjuangkan aspirasi masyarakat diDapil V Jateng yang meliputi wilayah Boyolali, Klaten, Sukoharjo dan Surakarta.\n\n\n"Saya ingin menunjukkan kepada masyarakat bahwa saya siap berkorban dan bekerja keras untuk memperjuangkan aspirasi mereka, meski prosesnya tidak mudah dan penuh tantangan," ujarnya.\nDia memperkirakan butuh waktu 11 hari untuk bisa sampai ke Boyolali. Ia juga sudah menyiapkan tim medis untuk mengantisipasi ada masalah di tengah perjalanan.\nDidik mengatakan ada 11 pos pemberhentian dalam perjalanannya ke Boyolali.\n"Perkiraan ada 11 pos (pemberhentian), dan kemungkinan maksimal ada 11 hari (perjalanan) kalau semua lancar, karena juga tergantung dengan situasi cuaca," kata Didik.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Anggota DPR Klaim Akan Jalan Kaki Jakarta-Boyolali, Target 11 Hari Anggota DPR RI dari Dapil V Jawa Tengah, Didik Haryadi mengaku akan berjalan kaki dari Jakarta menuju Boyolali, Jawa Tengah sebagai bentuk menunaikan janji. Perjalanan dimulai dari kawasan parlemen di Senayan, Jakarta ke Boyolali, hari ini, Rabu (1/1).\nDilansir dari Antara, Didik mengatakan jalan kaki ini adalah pelaksanaan dari janjinya kepada Allah.\n"Setiap orang pernah berjanji di hadapan Tuhan, dan saya ingin menepati janji itu selama saya masih diberi kesempatan hidup," kata Didik di kompleks parlemen, Senayan, Jakarta, Rabu (1/1).\nADVERTISEMENT\nSCROLL TO CONTINUE WITH CONTENT\n\nSelain itu ia juga mengaku pernah bernazar bila terpilih menjadi anggota DPR RI maka akan berjalan kaki dari Senayan, Jakarta, menuju Boyolali.\nNazar ini menurutnya jadi bentuk komitmen dirinya untuk memperjuangkan aspirasi masyarakat diDapil V Jateng yang meliputi wilayah Boyolali, Klaten, Sukoharjo dan Surakarta.\n\n\n"Saya ingin menunjukkan kepada masyarakat bahwa saya siap berkorban dan bekerja keras untuk memperjuangkan aspirasi mereka, meski prosesnya tidak mudah dan penuh tantangan," ujarnya.\nDia memperkirakan butuh waktu 11 hari untuk bisa sampai ke Boyolali. Ia juga sudah menyiapkan tim medis untuk mengantisipasi ada masalah di tengah perjalanan.\nDidik mengatakan ada 11 pos pemberhentian dalam perjalanannya ke Boyolali.\n"Perkiraan ada 11 pos (pemberhentian), dan kemungkinan maksimal ada 11 hari (perjalanan) kalau semua lancar, karena juga tergantung dengan situasi cuaca," kata Didik.\n

In [30]:
# --- VALIDASI PENGGABUNGAN TEKS SECARA UTUH (TURNBACKHOAX) ---

# 1. Matikan batasan lebar kolom agar teks terlihat semua
pd.set_option('display.max_colwidth', None)

# 2. Tetap tampilkan 10 baris secara manual (5 atas, 5 bawah)
pd.set_option('display.max_rows', 10)

print("--- Preview Hasil Penggabungan Turnbackhoax (Teks Utuh) ---")

# Menampilkan 5 data teratas untuk melihat awal dataset
display(df_tbh[['Title', 'FullText', 'text_original']].head(5))

print("-" * 30 + " Dan seterusnya (Data Tengah) " + "-" * 30)

# Menampilkan 5 data terbawah untuk melihat akhir dataset
display(df_tbh[['Title', 'FullText', 'text_original']].tail(5))

--- Preview Hasil Penggabungan Turnbackhoax (Teks Utuh) ---

                                                                            Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             FullText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               text_original
0                               najwa shihab diteror usai komentari video prabowo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Akun TikTok @beritatangguh mengunggah video dengan klaim bahwa jurnalis senior, Najwa Shihab, menerima teror dan ancaman setelah dirinya memberikan komentar mengenai video Prabowo Subianto di acara Debat Cawapres pada 22 Desember 2023. Dalam momen tersebut, diketahui bahwa Prabowo sempat menarik kerah jaket yang dipakai Menteri Investasi, Bahlil Lahadalia. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Najwa Shihab telah mengomentari video Prabowo yang menarik kerah jaket Bahlil. Sehingga, klaim bahwa Najwa Shihab mendapat ancaman setelah mengomentari video Prabowo tidak dapat dibuktikan kebenarannya. Meski demikian, diketahui melalui podcast Denny Sumargo, Najwa Shihab bercerita bahwa ia memang kerap menerima ancaman dan peretasan akun redaksi. Salah satu ancaman dan peretasan tersebut ia dapatkan ketika sedang melakukan investigasi terhadap beberapa kasus seperti kasus Ferdy Sambo, penjara mewah milik koruptor, dan mafia bola. Dengan demikian, informasi yang disebarluaskan oleh akun TikTok @beritatangguh merupakan informasi yang salah.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              najwa shihab diteror usai komentari video prabowo Akun TikTok @beritatangguh mengunggah video dengan klaim bahwa jurnalis senior, Najwa Shihab, menerima teror dan ancaman setelah dirinya memberikan komentar mengenai video Prabowo Subianto di acara Debat Cawapres pada 22 Desember 2023. Dalam momen tersebut, diketahui bahwa Prabowo sempat menarik kerah jaket yang dipakai Menteri Investasi, Bahlil Lahadalia. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Najwa Shihab telah mengomentari video Prabowo yang menarik kerah jaket Bahlil. Sehingga, klaim bahwa Najwa Shihab mendapat ancaman setelah mengomentari video Prabowo tidak dapat dibuktikan kebenarannya. Meski demikian, diketahui melalui podcast Denny Sumargo, Najwa Shihab bercerita bahwa ia memang kerap menerima ancaman dan peretasan akun redaksi. Salah satu ancaman dan peretasan tersebut ia dapatkan ketika sedang melakukan investigasi terhadap beberapa kasus seperti kasus Ferdy Sambo, penjara mewah milik koruptor, dan mafia bola. Dengan demikian, informasi yang disebarluaskan oleh akun TikTok @beritatangguh merupakan informasi yang salah.
1                                         video jokowi menyaksikan debat cawapres                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Sebuah akun TikTok membagikan video yang menampilkan Presiden Jokowi tengah menyaksikan Debat Calon Wakil Presiden (Cawapres) pada 22 Desember lalu. Video itu memperlihatkan foto Jokowi dari belakang menggunakan kaos kasual berwarna hijau tosca. Terdapat layar monitor yang cukup besar di depan Jokowi, layar itu menampilkan sesi debat cawapres. Faktanya unggahan TikTok tersebut merupakan hasil manipulasi, pengunggah menggabungkan foto dan video dalam satu frame. Hal ini membuat video seperti nyata jika Jokowi menyaksikan debat Cawapres. Berdasarkan penelusuran Google Image Search, ditemukan foto yang identik pada foto Jokowi yang menggunakan kaos kasual berwarna hijau tosca. Foto tersebut pernah diunggah di laman rri.go.id pada 17 Mei 2023. Judul artikel unggahan artikel RRI berjudul ” Momen Presiden Nobar Final Timnas U-22 SEA Games.” Saat itu Jokowi menyaksikan final Sea Games Indonesia vs Thailand di rumah dinas Walikota Medan. Sedangkan video yang ditampilkan pada layar di hadapan Jokowi, merupakan tayangan debat yang disiarkan oleh kanal Youtube KPU RI. Dengan demikian, unggahan yang menampilkan Jokowi sedang menyaksikan debat cawapres adalah salah. Unggahan tersebut termasuk dalam kategori konten yang dimanipulasi.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             video jokowi menyaksikan debat cawapres Sebuah akun TikTok membagikan video yang menampilkan Presiden Jokowi tengah menyaksikan Debat Calon Wakil Presiden (Cawapres) pada 22 Desember lalu. Video itu memperlihatkan foto Jokowi dari belakang menggunakan kaos kasual berwarna hijau tosca. Terdapat layar monitor yang cukup besar di depan Jokowi, layar itu menampilkan sesi debat cawapres. Faktanya unggahan TikTok tersebut merupakan hasil manipulasi, pengunggah menggabungkan foto dan video dalam satu frame. Hal ini membuat video seperti nyata jika Jokowi menyaksikan debat Cawapres. Berdasarkan penelusuran Google Image Search, ditemukan foto yang identik pada foto Jokowi yang menggunakan kaos kasual berwarna hijau tosca. Foto tersebut pernah diunggah di laman rri.go.id pada 17 Mei 2023. Judul artikel unggahan artikel RRI berjudul ” Momen Presiden Nobar Final Timnas U-22 SEA Games.” Saat itu Jokowi menyaksikan final Sea Games Indonesia vs Thailand di rumah dinas Walikota Medan. Sedangkan video yang ditampilkan pada layar di hadapan Jokowi, merupakan tayangan debat yang disiarkan oleh kanal Youtube KPU RI. Dengan demikian, unggahan yang menampilkan Jokowi sedang menyaksikan debat cawapres adalah salah. Unggahan tersebut termasuk dalam kategori konten yang dimanipulasi.
2                 nasdem akui terima aliran dana korupsi dari syahrul yasin limpo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Akun TikTok @r4kyatjelata mengunggah video dengan klaim bahwa Partai Nasional Demokrat (NasDem) mengaku telah menerima aliran dana korupsi dari mantan Menteri Pertanian, Syahrul Yasin Limpo (SYL), yang sebelumnya diduga menikmati hasil uang korupsi senilai Rp 13,9 M. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Partai NasDem mengaku telah menerima aliran dana korupsi dari SYL seperti yang tertulis pada unggahan. Partai NasDem melalui bendahara umumnya, Ahmad Sahroni, mengungkap bahwa SYL memang pernah memberikan uang ke Fraksi NasDem sebesar Rp 20 juta untuk bantuan bencana alam. Namun, mereka tidak mengetahui asal-usul uang dari SYL tersebut. Meski demikian, Partai NasDem telah mempersilakan KPK untuk menyelidiki dugaan mengalirnya uang korupsi SYL ke partai pimpinan Surya Paloh itu. Dengan demikian, informasi yang disebarluaskan oleh akun TikTok @r4kyatjelata merupakan informasi yang salah.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nasdem akui terima aliran dana korupsi dari syahrul yasin limpo Akun TikTok @r4kyatjelata mengunggah video dengan klaim bahwa Partai Nasional Demokrat (NasDem) mengaku telah menerima aliran dana korupsi dari mantan Menteri Pertanian, Syahrul Yasin Limpo (SYL), yang sebelumnya diduga menikmati hasil uang korupsi senilai Rp 13,9 M. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Partai NasDem mengaku telah menerima aliran dana korupsi dari SYL seperti yang tertulis pada unggahan. Partai NasDem melalui bendahara umumnya, Ahmad Sahroni, mengungkap bahwa SYL memang pernah memberikan uang ke Fraksi NasDem sebesar Rp 20 juta untuk bantuan bencana alam. Namun, mereka tidak mengetahui asal-usul uang dari SYL tersebut. Meski demikian, Partai NasDem telah mempersilakan KPK untuk menyelidiki dugaan mengalirnya uang korupsi SYL ke partai pimpinan Surya Paloh itu. Dengan demikian, informasi yang disebarluaskan oleh akun TikTok @r4kyatjelata merupakan informasi yang salah.
3  nama anies baswedan masuk dalam daftar penikmat uang hasil korupsi bts kominfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Akun TikTok @matanies mengunggah video dengan klaim bahwa nama Anies Baswedan masuk dalam daftar penikmat uang hasil korupsi proyek BTS 4G Kementerian Komunikasi dan Informatika (Kominfo) yang melibatkan mantan Sekjen Nasdem, Johnny G. Plate. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Anies Baswedan turut menikmati uang hasil korupsi BTS 4G Kominfo seperti yang diklaim pada unggahan. Berdasarkan artikel milik CNN Indonesia berjudul “Daftar 16 Tersangka Perkara Korupsi Proyek BTS Bakti Kominfo”, tidak ditemukan nama Anies Baswedan dalam daftar tersangka yang ditetapkan oleh Kejaksaan Agung (Kejagung) pada kasus korupsi BTS 4G Kominfo. Sebelumnya diketahui bahwa mantan Menteri Kominfo, Johnny G. Plate, telah ditahan usai ditetapkan sebagai tersangka kasus dugaan korupsi proyek penyediaan infrastruktur BTS 4G Bakti Kominfo oleh Kejagung. Diduga kasus korupsi ini merugikan negara hingga Rp 8 triliun. Dengan demikian, informasi yang disebarluaskan oleh akun TikTok @matanies merupakan informasi yang salah.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nama anies baswedan masuk dalam daftar penikmat uang hasil korupsi bts kominfo Akun TikTok @matanies mengunggah video dengan klaim bahwa nama Anies Baswedan masuk dalam daftar penikmat uang hasil korupsi proyek BTS 4G Kementerian Komunikasi dan Informatika (Kominfo) yang melibatkan mantan Sekjen Nasdem, Johnny G. Plate. Setelah dilakukan penelusuran, faktanya tidak ditemukan bukti kredibel yang menunjukkan bahwa Anies Baswedan turut menikmati uang hasil korupsi BTS 4G Kominfo seperti yang diklaim pada unggahan. Berdasarkan artikel milik CNN Indonesia berjudul “Daftar 16 Tersangka Perkara Korupsi Proyek BTS Bakti Kominfo”, tidak ditemukan nama Anies Baswedan dalam daftar tersangka yang ditetapkan oleh Kejaksaan Agung (Kejagung) pada kasus korupsi BTS 4G Kominfo. Sebelumnya diketahui bahwa mantan Menteri Kominfo, Johnny G. Plate, telah ditahan usai ditetapkan sebagai tersangka kasus dugaan korupsi proyek penyediaan infrastruktur BTS 4G Bakti Kominfo oleh Kejagung. Diduga kasus korupsi ini merugikan negara hingga Rp 8 triliun. Dengan demikian, informasi yang disebarluaskan oleh akun TikTok @matanies merupakan informasi yang salah.

------------------------------ Dan seterusnya (Data Tengah) ------------------------------

                                                                     Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       FullText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text_original
1479        penipuan prabowo kabulkan kenaikan gaji nakes dan guru honorer  Tim Pemeriksa Fakta Mafindo (TurnBackHoax) memastikan kebenaran klaim dengan memasukkan kata kunci “Prabowo kabulkan kenaikan gaji tenaga kesehatan dan guru honorer” ke mesin pencarian Google. Namun, tidak ditemukan satu pun pemberitaan media kredibel mengenai hal itu. Penelusuran berlanjut dengan mengakses laman media online bungko news (yang terdapat dalam unggahan) dan mengetikkan kata kunci “Prabowo kabulkan kenaikan gaji nakes”. Hasilnya, tidak ditemukan berita atau artikel yang membahas klaim. Turnbackhoax kemudian mengeklik tautan dalam bio akun pengunggah. Diketahui, warganet diarahkan ke laman yang meminta nomor telepon dan kode OTP. Terakhir, TurnBackHoax mencari tahu keaslian foto unggahan lewat Google lens. Diketahui, foto tersebut merupakan unggahan akun X resmi Prabowo “prabowo”. Konteks aslinya adalah potongan dokumentasi saat Prabowo menghadiri Rapat Koordinasi Nasional (Rakornas) Pemerintah Pusat dan Daerah pada Kamis (7/11/2024). Tidak ada informasi mengenai pembahasan soal kenaikan gaji tenaga kesehatan dan guru honorer dalam unggahan tersebut. Unggahan berisi klaim “Prabowo kabulkan kenaikan gaji tenaga kesehatan dan guru honorer” merupakan konten palsu (fabricated content).  penipuan prabowo kabulkan kenaikan gaji nakes dan guru honorer Tim Pemeriksa Fakta Mafindo (TurnBackHoax) memastikan kebenaran klaim dengan memasukkan kata kunci “Prabowo kabulkan kenaikan gaji tenaga kesehatan dan guru honorer” ke mesin pencarian Google. Namun, tidak ditemukan satu pun pemberitaan media kredibel mengenai hal itu. Penelusuran berlanjut dengan mengakses laman media online bungko news (yang terdapat dalam unggahan) dan mengetikkan kata kunci “Prabowo kabulkan kenaikan gaji nakes”. Hasilnya, tidak ditemukan berita atau artikel yang membahas klaim. Turnbackhoax kemudian mengeklik tautan dalam bio akun pengunggah. Diketahui, warganet diarahkan ke laman yang meminta nomor telepon dan kode OTP. Terakhir, TurnBackHoax mencari tahu keaslian foto unggahan lewat Google lens. Diketahui, foto tersebut merupakan unggahan akun X resmi Prabowo “prabowo”. Konteks aslinya adalah potongan dokumentasi saat Prabowo menghadiri Rapat Koordinasi Nasional (Rakornas) Pemerintah Pusat dan Daerah pada Kamis (7/11/2024). Tidak ada informasi mengenai pembahasan soal kenaikan gaji tenaga kesehatan dan guru honorer dalam unggahan tersebut. Unggahan berisi klaim “Prabowo kabulkan kenaikan gaji tenaga kesehatan dan guru honorer” merupakan konten palsu (fabricated content).
1480          prabowo gaji tni harus naik dua kali lipat supaya lebih giat    Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama-tama memastikan kebenaran klaim dengan memasukkan kata kunci “Prabowo bilang gaji TNI naik dua kali lipat” ke mesin pencarian Google. Hasilnya, tidak ditemukan pemberitaan media mengenai hal itu. Melansir pemberitaan detik.com “Gaji PNS Naik Bertahap di 2025: Prioritas Guru, Nakes, dan TNI/Polri” yang tayang Sabtu (17/8/2024), Menteri Perencanaan Pembangunan Nasional/Kepala Bappenas—kala itu Suharso Monoarfa—menyebut kenaikan gaji merupakan satu dari delapan program Prabowo-Gibran yang sudah dimasukkan dalam postur RAPBN 2025. Suharso Monoarfa, mengatakan program kenaikan gaji ini merupakan bagian dari delapan program unggulan Prabowo-Gibran yang sudah dimasukkan dalam postur RAPBN 2025. Namun, tak disebutkan berapa persen peningkatannya. “Kenaikan gaji aparatur sipil negara terutama guru, dosen, tenaga kesehatan, penyuluh, serta TNI dan Polri akan dilakukan secara bertahap,” kata Suharso pada Agustus 2024. Tidak ditemukan informasi dari media kredibel yang membenarkan klaim tersebut. Video berisi narasi “Presiden Prabowo menyampaikan gaji TNI harus naik dua kali lipat supaya lebih giat” merupakan konten yang menyesatkan (misleading content).      prabowo gaji tni harus naik dua kali lipat supaya lebih giat Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama-tama memastikan kebenaran klaim dengan memasukkan kata kunci “Prabowo bilang gaji TNI naik dua kali lipat” ke mesin pencarian Google. Hasilnya, tidak ditemukan pemberitaan media mengenai hal itu. Melansir pemberitaan detik.com “Gaji PNS Naik Bertahap di 2025: Prioritas Guru, Nakes, dan TNI/Polri” yang tayang Sabtu (17/8/2024), Menteri Perencanaan Pembangunan Nasional/Kepala Bappenas—kala itu Suharso Monoarfa—menyebut kenaikan gaji merupakan satu dari delapan program Prabowo-Gibran yang sudah dimasukkan dalam postur RAPBN 2025. Suharso Monoarfa, mengatakan program kenaikan gaji ini merupakan bagian dari delapan program unggulan Prabowo-Gibran yang sudah dimasukkan dalam postur RAPBN 2025. Namun, tak disebutkan berapa persen peningkatannya. “Kenaikan gaji aparatur sipil negara terutama guru, dosen, tenaga kesehatan, penyuluh, serta TNI dan Polri akan dilakukan secara bertahap,” kata Suharso pada Agustus 2024. Tidak ditemukan informasi dari media kredibel yang membenarkan klaim tersebut. Video berisi narasi “Presiden Prabowo menyampaikan gaji TNI harus naik dua kali lipat supaya lebih giat” merupakan konten yang menyesatkan (misleading content).
1481                         tom lembong bocorkan bobrok jokowi ke prabowo                                                                                                                                                                                                                                                                                                                                                                                Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama-tama menelusuri kebenaran klaim dengan memasukkan kata kunci “Tom Lembong bocorkan bobrok Jokowi ke Prabowo” ke mesin pencarian Google. Hasilnya, tidak ditemukan informasi tentang Tom Lembong bocorkan bobrok Jokowi ke Prabowo. TurnBackHoax kemudian menelusuri sampul foto video lewat Google Lens dan tidak menemukan gambar serupa. Potret dalam sampul video merupakan hasil suntingan atau manipulasi dari penggabungan sejumlah gambar. Dari pengamatan TurnBackHoax, video berdurasi 51 menit 07 detik itu hanya menayangkan ulang video dari kanal YouTube Refly Harun “?LIVE! TOM LEMBONG BERSALAH SOAL IMPOR GULA? INI DENGAN (SAKSI) AHLI PROF DWI ANDREAS SANTOSA!!” yang tayang Kamis (21/11/2024). Tidak ada sumber kredibel yang membenarkan klaim tentang Tom Lembong bocorkan bobrok Jokowi ke Prabowo.                                                                                                                                                                                                                                                                                                                                                                                                 tom lembong bocorkan bobrok jokowi ke prabowo Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama-tama menelusuri kebenaran klaim dengan memasukkan kata kunci “Tom Lembong bocorkan bobrok Jokowi ke Prabowo” ke mesin pencarian Google. Hasilnya, tidak ditemukan informasi tentang Tom Lembong bocorkan bobrok Jokowi ke Prabowo. TurnBackHoax kemudian menelusuri sampul foto video lewat Google Lens dan tidak menemukan gambar serupa. Potret dalam sampul video merupakan hasil suntingan atau manipulasi dari penggabungan sejumlah gambar. Dari pengamatan TurnBackHoax, video berdurasi 51 menit 07 detik itu hanya menayangkan ulang video dari kanal YouTube Refly Harun “?LIVE! TOM LEMBONG BERSALAH SOAL IMPOR GULA? INI DENGAN (SAKSI) AHLI PROF DWI ANDREAS SANTOSA!!” yang tayang Kamis (21/11/2024). Tidak ada sumber kredibel yang membenarkan klaim tentang Tom Lembong bocorkan bobrok Jokowi ke Prabowo.
1482                    prabowo bakal posisikan polri di bawah naungan tni                                                                                                                                                                                                                                                                                                                                Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama-tama memastikan kebenaran klaim dengan memasukkan kata kunci “Prabowo akan posisikan Polri di bawah naungan TNI jika enggan berbenah institusi” ke mesin pencarian Google. Hasilnya, tidak ditemukan pemberitaan media kredibel yang relevan dengan klaim. TurnBackHoax kemudian menelusuri pencarian Google dengan kata kunci “Posisi Polri TNI di kabinet Prabowo”. Pencarian teratas mengarah ke pemberitaan sindonews.com “Perpres Kabinet Prabowo-Gibran: TNI, Polri, dan Kejagung di Bawah Budi Gunawan”. Dalam berita yang tayang Kamis (24/10/2024) itu, disebutkan bahwa di Kabinet Merah Putih Prabowo-Gibran, posisi Polri-TNI berada di bawah Kementerian Koordinator Bidang Politik, Hukum dan Keamanan. Unggahan berisi klaim “Prabowo bakal posisikan Polri di bawah naungan TNI jika enggan berbenah institusi” merupakan konten palsu (fabricated content).                                                                                                                                                                                                                                                                                                                                            prabowo bakal posisikan polri di bawah naungan tni Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama-tama memastikan kebenaran klaim dengan memasukkan kata kunci “Prabowo akan posisikan Polri di bawah naungan TNI jika enggan berbenah institusi” ke mesin pencarian Google. Hasilnya, tidak ditemukan pemberitaan media kredibel yang relevan dengan klaim. TurnBackHoax kemudian menelusuri pencarian Google dengan kata kunci “Posisi Polri TNI di kabinet Prabowo”. Pencarian teratas mengarah ke pemberitaan sindonews.com “Perpres Kabinet Prabowo-Gibran: TNI, Polri, dan Kejagung di Bawah Budi Gunawan”. Dalam berita yang tayang Kamis (24/10/2024) itu, disebutkan bahwa di Kabinet Merah Putih Prabowo-Gibran, posisi Polri-TNI berada di bawah Kementerian Koordinator Bidang Politik, Hukum dan Keamanan. Unggahan berisi klaim “Prabowo bakal posisikan Polri di bawah naungan TNI jika enggan berbenah institusi” merupakan konten palsu (fabricated content).
1483  pramono anung gusur warga nggak masalah yang penting kebijakan jalan                                                                                                                                                                                                                                                                                       Tim Pemeriksa Fakta Mafindo (TurnBackHoax) mencari kebenaran narasi dengan memasukkan kata kunci “apakah Pramono ingin gusur warga” ke mesin pencari Google. Hasilnya, ditemukan pemberitaan tempo.co dan cnnindonesia.com yang membantah klaim tersebut. Dalam laporan tempo.co yang tayang Selasa (5/11/2024), pihak Tim Pemenangan Pramono-Rano menegaskan narasi “Pramono Anung mengatakan bahwa menggusur warga nggak masalah, yang penting kebijakan jalan” merupakan hoaks. Dilansir dari berita cnnindonesia.com “Pramono: Catat Omongan Saya, Kalau Jadi Gubernur Saya Tak Menggusur” pada Senin (18/11/2024), Pramono berjanji tak akan melakukan penggusuran rumah warga apabila terpilih memimpin Jakarta bersama pasangannya, Rano Karno. Unggahan dengan narasi “Pramono Anung mengatakan bahwa menggusur warga nggak masalah, yang penting kebijakan jalan” merupakan konten yang menyesatkan (misleading content). (Ditulis oleh Moch. Marcellodiansyah)                                                                                                                                                                                                                                                                                 pramono anung gusur warga nggak masalah yang penting kebijakan jalan Tim Pemeriksa Fakta Mafindo (TurnBackHoax) mencari kebenaran narasi dengan memasukkan kata kunci “apakah Pramono ingin gusur warga” ke mesin pencari Google. Hasilnya, ditemukan pemberitaan tempo.co dan cnnindonesia.com yang membantah klaim tersebut. Dalam laporan tempo.co yang tayang Selasa (5/11/2024), pihak Tim Pemenangan Pramono-Rano menegaskan narasi “Pramono Anung mengatakan bahwa menggusur warga nggak masalah, yang penting kebijakan jalan” merupakan hoaks. Dilansir dari berita cnnindonesia.com “Pramono: Catat Omongan Saya, Kalau Jadi Gubernur Saya Tak Menggusur” pada Senin (18/11/2024), Pramono berjanji tak akan melakukan penggusuran rumah warga apabila terpilih memimpin Jakarta bersama pasangannya, Rano Karno. Unggahan dengan narasi “Pramono Anung mengatakan bahwa menggusur warga nggak masalah, yang penting kebijakan jalan” merupakan konten yang menyesatkan (misleading content). (Ditulis oleh Moch. Marcellodiansyah)

# Penggabungan Dataset (Merging)

In [31]:
columns_to_keep = ['Timestamp', 'text_original', 'label']
df_merged = pd.concat([df_cnn[columns_to_keep], df_tbh[columns_to_keep]], ignore_index=True)

In [35]:
# 1. Melihat informasi dasar dataset yang sudah digabung
print("--- INFO DATASET TERGABUNG (df_merged) ---")
df_merged.info()

--- INFO DATASET TERGABUNG (df_merged) ---
<class 'pandas.core.frame.DataFrame'>
Index: 4155 entries, 0 to 4158
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Timestamp      4155 non-null   object
 1   text_original  4155 non-null   object
 2   label          4155 non-null   int64
dtypes: int64(1), object(2)
memory usage: 129.8+ KB

In [36]:
# --- PREVIEW KESELURUHAN DATASET TERGABUNG ---

# 1. Hitung total sebelum di-drop (untuk laporan data mentah)
total_mentah = len(df_merged) 
print(f"--- Total Dataset Mentah: {total_mentah} Baris ---")

# 2. Proses pembersihan (yang bikin jumlahnya jadi 4.155)
df_merged.drop_duplicates(subset=['text_original'], keep='first', inplace=True)
total_bersih = len(df_merged)

print(f"--- Total Dataset Setelah Cleaning: {total_bersih} Baris ---")
print(f"--- (Dihapus {total_mentah - total_bersih} data duplikat) ---\n")

# 3. Pengaturan tampilan (5 atas, 5 bawah)
# max_rows 10 artinya pandas akan nampilin 5 awal dan 5 akhir kalau datanya banyak
pd.set_option('display.max_rows', 10) 
pd.set_option('display.max_colwidth', 100) # Biar teks original nggak kepanjangan

display(df_merged[['Timestamp', 'text_original', 'label']])

# Reset settingan display
pd.reset_option('display.max_rows')

--- Total Dataset Mentah: 4155 Baris ---
--- Total Dataset Setelah Cleaning: 4155 Baris ---
--- (Dihapus 0 data duplikat) ---

                Timestamp                                                                                        text_original  label
0     2024-01-04 00:00:00  Marzuki Mustamar Eks PWNU Jatim Ungkap Kejanggalan 3 SP dari PBNU Marzuki Mustamar buka-bukaan s...      0
1              04/01/2024  Revisi UU ITE Jilid II Resmi Berlaku, Sudah Diteken Jokowi Presiden Joko Widodo menandatangani r...      0
2              02/01/2024  Senator Bali Arya Wedakarna Buka Suara soal Viral Ucapan Hijab Anggota DPD RI atau senator asal ...      0
3              02/01/2024  PWNU Jatim Dapat Karangan Bunga Protes Pemecatan Marzuki Mustamar Kantor Pengurus Wilayah Nahdla...      0
4              02/01/2024  Jokowi Ingin Pulang ke Solo Usai Jabat Presiden: Jadi Rakyat Biasa Presiden Joko Widodo (Jokowi)...      0
...                   ...                                                                                                  ...    ...
4154           26/11/2024  penipuan prabowo kabulkan kenaikan gaji nakes dan guru honorer Tim Pemeriksa Fakta Mafindo (Turn...      1
4155           26/11/2024  prabowo gaji tni harus naik dua kali lipat supaya lebih giat Tim Pemeriksa Fakta Mafindo (TurnBa...      1
4156           26/11/2024  tom lembong bocorkan bobrok jokowi ke prabowo Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pertama...      1
4157           27/11/2024  prabowo bakal posisikan polri di bawah naungan tni Tim Pemeriksa Fakta Mafindo (TurnBackHoax) pe...      1
4158           27/11/2024  pramono anung gusur warga nggak masalah yang penting kebijakan jalan Tim Pemeriksa Fakta Mafindo...      1

[4155 rows x 3 columns]

In [18]:
# 4. Mengecek distribusi label untuk memastikan tidak ada data yang hilang
print("\n--- Jumlah Data Per Label ---")
print(df_merged['label'].value_counts().rename({0: 'Valid (CNN)', 1: 'Hoax (TBH)'}))

--- Jumlah Data Per Label ---
label
Valid (CNN)    2675
Hoax (TBH)     1484
Name: count, dtype: int64

# Data Cleaning Tingkat Awal (Rendudancy)

In [19]:
df_merged.dropna(subset=['text_original'], inplace=True)
duplicate_count = df_merged.duplicated(subset=['text_original']).sum()
df_merged.drop_duplicates(subset=['text_original'], keep='first', inplace=True)

In [20]:
# Mengecek apakah ada kolom yang kosong (null) setelah penggabungan
print("\n--- Pengecekan Missing Values ---")
print(df_merged.isnull().sum())

--- Pengecekan Missing Values ---
Timestamp        0
text_original    0
label            0
dtype: int64

In [23]:
# Identifikasi Data Redundan (Duplikat) Sebelum Pembersihan
# Menggabungkan data sementara untuk pengecekan kualitas dataset
df_temp = pd.concat([df_cnn[['Timestamp', 'text_original', 'label']], 
                     df_tbh[['Timestamp', 'text_original', 'label']]], ignore_index=True)

# Mengekstraksi seluruh baris yang memiliki kesamaan konten teks (redundansi)
df_tampil_duplikat = df_temp[df_temp.duplicated(subset=['text_original'], keep=False)]

print(f"--- Visualisasi Data Duplikat Terdeteksi (Total: {len(df_tampil_duplikat)} entri) ---")

# Menampilkan sampel data duplikat berdasarkan urutan teks untuk validasi kualitatif
display(df_tampil_duplikat.sort_values(by='text_original').head(8))

--- Visualisasi Data Duplikat Terdeteksi (Total: 8 entri) ---

       Timestamp                                      text_original  label
3057  29/02/2024  anak yang hina jokowi terancam 7 tahun penjara...      1
3123  10/03/2024  anak yang hina jokowi terancam 7 tahun penjara...      1
3314  09/04/2024  cina ingin pindahkan warganya ke indonesia Seb...      1
3317  09/04/2024  cina ingin pindahkan warganya ke indonesia Seb...      1
3365  23/04/2024  kfc menghina para pengungsi palestina Beredar ...      1
3366  23/04/2024  kfc menghina para pengungsi palestina Beredar ...      1
2916  14/02/2024  video prabowo boleh jual negeri kepada pihak a...      1
3172  14/03/2024  video prabowo boleh jual negeri kepada pihak a...      1

In [24]:
print("\n--- Pembersihan Duplikat ---")
print(f"Jumlah data duplikat yang dihapus: {duplicate_count}")
print(f"Total data setelah pembersihan: {len(df_merged)}")

--- Pembersihan Duplikat ---
Jumlah data duplikat yang dihapus: 4
Total data setelah pembersihan: 4155

# Shuffling Data

In [25]:
df_final = df_merged.sample(frac=1, random_state=42).reset_index(drop=True)

In [26]:
print("\n--- Distribusi Label Akhir ---")
print(df_final['label'].value_counts().rename({0: 'CNN (Valid)', 1: 'TBH (Hoax)'}))

--- Distribusi Label Akhir ---
label
CNN (Valid)    2675
TBH (Hoax)     1480
Name: count, dtype: int64

In [27]:
# Menampilkan hasil
pd.set_option('display.max_rows', 10)

print(f"\n--- Visualisasi Struktur Dataset Akhir (Total: {len(df_final)} Baris) ---")
# Menampilkan struktur dataset dengan representasi baris awal dan akhir (ellipses)
display(df_final[['Timestamp', 'text_original', 'label']])

--- Visualisasi Struktur Dataset Akhir (Total: 4155 Baris) ---

       Timestamp                                      text_original  label
0     29/11/2024  Habiburokhman soal Polisi Tembak Siswa: Seenak...      0
1     26/04/2024  video anak anak gaza mendapat kesempatan berma...      1
2     18/02/2024  video hari ini ditemukan oleh relawan anies di...      1
3     15/11/2024  anies bongkar misi busuk prabowo usai tom lemb...      1
4     12/06/2024  video demo cirebon pada 1 juni 2024 Akun Tikto...      1
...          ...                                                ...    ...
4150  13/05/2024  video warga israel kabur dengan tangga eskalat...      1
4151  12/04/2024  Puan Berkebaya Kuning Saat Rayakan Lebaran den...      0
4152  03/03/2024  frasa agama akan dihapus dalam peta jalan pend...      1
4153  13/08/2024  samsung menarik iklan senilai 1 miliar dengan ...      1
4154  08/06/2024  PDIP Nilai Lebih Cocok Menteri, Emil Dardak Pa...      0

[4155 rows x 3 columns]

In [30]:
# Preview hasil akhir data preparation
pd.set_option('display.max_rows', 10) 

print(f"--- Visualisasi Dataset (Total: {len(df_final)} Baris) ---")
display(df_final[['Timestamp', 'text_original', 'label']])

--- Visualisasi Dataset (Total: 4155 Baris) ---

       Timestamp                                      text_original  label
0     29/11/2024  Habiburokhman soal Polisi Tembak Siswa: Seenak...      0
1     26/04/2024  video anak anak gaza mendapat kesempatan berma...      1
2     18/02/2024  video hari ini ditemukan oleh relawan anies di...      1
3     15/11/2024  anies bongkar misi busuk prabowo usai tom lemb...      1
4     12/06/2024  video demo cirebon pada 1 juni 2024 Akun Tikto...      1
...          ...                                                ...    ...
4150  13/05/2024  video warga israel kabur dengan tangga eskalat...      1
4151  12/04/2024  Puan Berkebaya Kuning Saat Rayakan Lebaran den...      0
4152  03/03/2024  frasa agama akan dihapus dalam peta jalan pend...      1
4153  13/08/2024  samsung menarik iklan senilai 1 miliar dengan ...      1
4154  08/06/2024  PDIP Nilai Lebih Cocok Menteri, Emil Dardak Pa...      0

[4155 rows x 3 columns]

In [28]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4155 entries, 0 to 4154
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Timestamp      4155 non-null   object
 1   text_original  4155 non-null   object
 2   label          4155 non-null   int64
dtypes: int64(1), object(2)
memory usage: 97.5+ KB

# Export Hasil

In [16]:
output_file = 'dataset_merged_labeled.xlsx'
df_final.to_excel(output_file, index=False)

print(f"\n--- Proses File 1 Selesai ---")
print(f"Data tersimpan di: {output_file}")

--- Proses File 1 Selesai ---
Data tersimpan di: dataset_merged_labeled.xlsx